on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_e888d0e8_a9a7_4d4d_96b8_f383dfe933ac_API_KEY }}
          config_path_input: 'openfn-e888d0e8-a9a7-4d4d-96b8-f383dfe933ac-config.json'
